feat(Request Data Collector): Add RequestResponseCollector and DatabaseCollector
miquido/request-data-collector pull request #1
Opened 2019-03-28 12:18 UTC by donatorsky

Add RequestResponseCollector and DatabaseCollector.

2019-03-28 12:33 UTC, maksymilian-lewicki requested changes
Rename namespaces to Miquido in all files

2019-03-28 12:33 UTC, maksymilian-lewicki commented on .editorconfig
> +[VERSION]
We don't have `VERSION` file.

2019-03-28 12:33 UTC, maksymilian-lewicki commented on README.md
> +		\Pitched\RequestDataCollector\RequestDataCollectorServiceProvider,
rename `Pitched` to `Miquido`

2019-03-28 12:33 UTC, maksymilian-lewicki commented on config/request-data-collector.php
> +            'filter' => \Pitched\RequestDataCollector\Filters\UserAgentFilter::class,
rename `Pitched` to `Miquido`

2019-03-29 09:23 UTC, miquido-legenc approved these changes

2019-03-29 09:31 UTC, maksymilian-lewicki approved these changes

2019-03-29 09:42 UTC, merged